### ISSUE TITLE
peerDependency support for Jest

### ISSUE THREAD

**Issue by jdmunro** [unindented/jasmine-immutable-matchers#31]
I've been using this with [Jest](https://facebook.github.io/jest/) for months without issue.

There's just one minor thing:

> npm WARN jasmine-immutable-matchers@1.0.1 requires a peer of jasmine-core@^2.0 but none was installed.

This library correctly has a peer-dependency on jasmine-core. However, with Jest, it ships with its own internal dependency on Jasmine and so there is no requirement for an explicit top-level dependency on jasmine-core.

Do you see any issue with adding a || to the peerDependency to support jasmine-core or jest?

**Comment by unindented** [comment]
Nice to hear! I didn't know you could have `||` in the `peerDependency` field. Would you mind opening a PR with the change?

**Comment by jdmunro** [comment]
> I didn't know you could have || in the peerDependency field.

I just realised I made this up 🙈 

I'll see if there's an alternative way to support both.

**Comment by unindented** [comment]
@jdmunro I've also moved to `jest`, and I also find this annoying, so I've just removed `peerDependencies` altogether.

**Comment by jdmunro** [comment]
Hey @unindented - thanks!
