### ISSUE TITLE
Breaking changes from 1.0.1

### ISSUE THREAD

**Issue by yarcub** [unindented/jasmine-immutable-matchers#32]
Hi.

Since the minor bump to `1.1.0`, specs on my project started failing with:
```
TypeError: undefined is not a function (evaluating 'expect(result).toEqualImmutable(expectedState)')
```

It is ok with `1.0.1`. Do jasmine needs to be updated as well?
```
├─ jasmine-core@2.4.1
├─ jasmine-immutable-matchers@1.0.1
├─ karma-jasmine-html-reporter@0.2.2
│  ├─ karma-jasmine@^1.0.2
│  └─ karma-jasmine@1.0.2
├─ karma-jasmine@0.3.8
```

**Comment by unindented** [comment]
Let me check what's going on.

**Comment by unindented** [comment]
@yarcub how do you import `jasmine-immutable-matchers` and then add them to `jasmine`? Can you paste the bit of code?

**Comment by unindented** [comment]
I suspect your issue has to do with ES2015 default imports, so I've added a [new section in the `README`](https://github.com/unindented/jasmine-immutable-matchers#es2015).

**Comment by yarcub** [comment]
```javascript
import matchers from 'jasmine-immutable-matchers'

beforeEach(function () {
  jasmine.addMatchers(matchers)
})
```
It's expecting an default export. Will change it to import all as in  README. 👍

**Comment by unindented** [comment]
Awesome, thank you!
