### ISSUE TITLE
Show deep comparison on failure

### ISSUE THREAD

**Issue by AlanFoster** [unindented/jasmine-immutable-matchers#33]
Firstly, thanks for the great plugin for Jasmine :+1:

I have a small request to add a nice comparison between the two objects

This request is inspired by the chai immutable library, which given the test-setup

```js
import chaiImmutable from 'chai-immutable';

chai.use(chaiImmutable);
```

With the test file:

```js
import { expect } from 'chai';
import Immutable from 'immutable';

describe('Chai Immutable Comparisons', function () {
  it('Outputs a comparison on failure for different map values', function () {
    expect(Immutable.Map({ a: 20, b: 20 })).to.equal(Immutable.Map({ a: 22 }));
  });
});
```

Provides a nice visual difference of 

![image](https://cloud.githubusercontent.com/assets/1271782/20523571/9e814dd8-b0ad-11e6-9ce1-0abee2ed7e19.png)

This comparison works for deeply nested objects too

**Comment by unindented** [comment]
Yeah, you are totally right. I'll look into this.

**Comment by unindented** [comment]
I just checked, and `chai-immutable` and this library are doing the same: just calling `toString` on the objects. It's `chai` itself the one that provides the nice green/red diff. We should request this in the `jasmine` project I guess?
